recipe_app/recipe_posts/forms.py
#Recipe Form 

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed, FileRequired
from flask_uploads import UploadSet, configure_uploads, IMAGES


class RecipePostForm(FlaskForm):
   

    ###############################################################
    recipe_image = FileField('Uplod_Recipe_Image', validators=[FileAllowed(IMAGES, 'Images only!')])
    
    ########################################################################

    recipe_name = StringField('Recipe_Name', validators=[DataRequired()])
    #####################################################################
    course = StringField('Course', validators=[DataRequired()])
    food_category = StringField('Food_Category', validators=[DataRequired()])
    cuisine = StringField('Cuisine', validators=[DataRequired()])
    prep_time = StringField('Prep_Time', validators=[DataRequired()])
    cook_time = StringField('Cook_Time', validators=[DataRequired()])
    allergens = StringField('Allergens', validators=[DataRequired()])
    serving = StringField('Serving', validators=[DataRequired()])
    ##########################
    ingredients = TextAreaField('Ingredients', validators=[DataRequired()])
    recipe_description = TextAreaField('Recipe_Description', validators=[DataRequired()])
    submit = SubmitField('Post-Your-Receipe')

#########################################

recipe_app/core/views.py
#Core.Views

from flask import render_template, request, Blueprint
from recipe_app.models import RecipePost

core = Blueprint('core',__name__)

@core.route('/')
def index():
    '''
    This is the home page view. Notice how it uses pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    '''
    page = request.args.get('page', 1, type=int)
    all_recipies_posts = RecipePost.query.order_by(RecipePost.date.desc()).paginate(page=page, per_page=10)
    return render_template('index.html', all_recipies_posts = all_recipies_posts)

@core.route('/info')
def info():
    return render_template('info.html')

recipe_app/recipe_posts/views.py
#Views Blog_Post
import os
from flask import render_template,url_for,flash, redirect,request,Blueprint
from flask_login import current_user, login_required
from recipe_app import db
from recipe_app import app

from recipe_app.models import RecipePost
from recipe_app.recipe_posts.forms import RecipePostForm
from werkzeug import FileStorage
from werkzeug.utils import secure_filename
from recipe_app.tools import upload_file_to_s3, list_files_in_s3, delete_file_from_s3

recipe_posts = Blueprint('recipe_posts',__name__)

@recipe_posts.route('/create',methods=['GET','POST'])
@login_required
def create_recipe():
    form = RecipePostForm()

    if form.validate_on_submit():

        #########################

        file            = request.files["recipe_image"]
        output          = upload_file_to_s3(file, app.config["S3_BUCKET"])
        filename        = file.filename
        image_url       = str(output)

        ##################################

        recipe_post = RecipePost(recipe_image = image_url,
                             ########################
                             recipe_name=form.recipe_name.data,
                             course=form.course.data,
                             food_category=form.food_category.data,
                             cuisine=form.cuisine.data,
                             prep_time=form.prep_time.data,
                             cook_time=form.cook_time.data,
                             allergens=form.allergens.data,
                             serving=form.serving.data,
                             ##########################
                             ingredients=form.ingredients.data,
                             recipe_description=form.recipe_description.data,
                             user_id=current_user.id
                             )
        db.session.add(recipe_post)
        db.session.commit()
        flash("Recipe Post Created", 'success')
        return redirect(url_for('core.index'))

    return render_template('create_recipe.html',form=form)


# int: recipe_post_id gets passed as in integer
# instead of a string so we can look it up later.

#read or view the Single Recipe Details
@recipe_posts.route('/<int:recipe_post_id>')
def recipe_post(recipe_post_id):
    # grab the requested recipe post by id number or return 404
    recipe_post = RecipePost.query.get_or_404(recipe_post_id)
    return render_template('recipe_post.html', recipe_name=recipe_post.recipe_name,
                            date=recipe_post.date, recipe=recipe_post
    )

#Update the recipe
@recipe_posts.route("/<int:recipe_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(recipe_post_id):
    recipe_post = RecipePost.query.get_or_404(recipe_post_id)
    if recipe_post.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = RecipePostForm()

    if form.validate_on_submit():
        if form.recipe_image.has_file():

            #############################
            file            = request.files["recipe_image"]
            output          = upload_file_to_s3(file, app.config["S3_BUCKET"])
            filename        = file.filename
            image_url       = str(output)
            ###########################
            
            
            recipe_post.recipe_image = image_url
        else:
            image_url = recipe_post.recipe_image

        ##################################################################################################################
        recipe_post.recipe_name = form.recipe_name.data
        #######################################
        recipe_post.course=form.course.data
        recipe_post.food_category=form.food_category.data
        recipe_post.cuisine=form.cuisine.data
        recipe_post.prep_time=form.prep_time.data
        recipe_post.cook_time=form.cook_time.data
        recipe_post.allergens=form.allergens.data
        recipe_post.serving=form.serving.data

        #######################################

        recipe_post.ingredients = form.ingredients.data
        recipe_post.recipe_description = form.recipe_description.data

        db.session.commit()
        flash(f'Recipe Updated!', 'success')
        return redirect(url_for('recipe_posts.recipe_post', recipe_post_id=recipe_post.id))
        
    # Pass back the old recipe post information so they can start again with
    # the old text and title.

    elif request.method == 'GET':

        ########################################
        form.recipe_name.data = recipe_post.recipe_name
        ########################################
        form.course.data = recipe_post.course
        form.food_category.data = recipe_post.food_category
        form.cuisine.data = recipe_post.cuisine
        form.prep_time.data = recipe_post.prep_time
        form.cook_time.data = recipe_post.cook_time
        form.allergens.data = recipe_post.allergens
        form.serving.data =recipe_post.serving
        ################################################
        form.ingredients.data = recipe_post.ingredients
        form.recipe_description.data = recipe_post.recipe_description
    return render_template('create_recipe.html', title='Update',
                           form=form)

#Delete the recipe
@recipe_posts.route("/<int:recipe_post_id>/delete", methods=['POST'])
@login_required
def delete_recipe(recipe_post_id):
    recipe_post = RecipePost.query.get_or_404(recipe_post_id)
    if recipe_post.author != current_user:
        abort(403)
    db.session.delete(recipe_post)
    db.session.commit()
    flash(f'Recipe Deleted!', 'danger')
    return redirect(url_for('core.index'))


######################################################################################

recipe_app/users/views.py
#user views
from sqlalchemy.exc import IntegrityError
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from recipe_app import db
from recipe_app import app
from werkzeug.urls import url_parse

#from recipe_app import fhotos
from recipe_app.models import User, RecipePost
from recipe_app.users.forms import RegistrationForm, LoginForm, UpdateUserForm, \
    ResetPasswordRequestForm, ResetPasswordForm

from werkzeug import FileStorage
from werkzeug.utils import secure_filename
from recipe_app.tools import upload_file_to_s3, list_files_in_s3, delete_file_from_s3
from recipe_app.email import send_password_reset_email


users = Blueprint('users', __name__)

# register
@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        try:
            user = User(email=form.email.data,
                        username=form.username.data,
                        password=form.password.data
                        )

            db.session.add(user)
            db.session.commit()
            flash(f'Account created for {form.username.data}!', 'success')
            return redirect(url_for('users.login'))

        except IntegrityError:
            db.session.rollback()
            flash(f'either email {form.email.data} or username {form.username.data} already taken : !', 'danger')
            

    return render_template('register.html', form=form)



# login
@users.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        #if user.check_password(form.password.data) and user is not None:
        if user is not None and user.check_password(form.password.data):

            login_user(user)
            flash('You have been logged in!', 'success')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
        else:flash('Login Unsuccessful. Please check username and password', 'danger')

    return render_template('login.html',form=form)


# logout
@users.route("/logout")
def logout():
    logout_user()
    flash('You have been logged Out!', 'success')
    return redirect(url_for("core.index"))


# account (update UserForm)
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():

        ####################################################################
        if form.picture.has_file():

            #############################
            file            = request.files["picture"]
            output          = upload_file_to_s3(file, app.config["S3_BUCKET"])
            filename        = file.filename
            image_url       = str(output)
            ###########################


            if current_user.picture is not None and current_user.picture != image_url:
                flash("User picture updated")
            current_user.picture = image_url

        else:
            image_url = current_user.picture

        ##############################################################
        try:
            if current_user.username is not None and current_user.username != form.username.data:
                #flash("User name updated")
                current_user.username = form.username.data
            
            ##############################################################
            
            if current_user.email is not None and current_user.email != form.email.data:
                #flash("User email updated")
                current_user.email = form.email.data

            ##############################################################
            db.session.commit()

        except IntegrityError:
            db.session.rollback()
            flash(f'either email {form.email.data} or username {form.username.data} already taken : !', 'danger')

        
        return redirect(url_for('users.account'))
        ##############################################################

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', form=form)


# get all the recipe of user

@users.route("/<username>")
def user_recipies(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    recipies_posted = RecipePost.query.filter_by(author=user).order_by(RecipePost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_recipe_posts.html', recipies_posted=recipies_posted, user=user)

##################### rest password ##############################


@users.route('/reset_password_request', methods=['GET', 'POST'])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for('core.index'))
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_password_reset_email(user)
        flash('Check your email for the instructions to reset your password')
        return redirect(url_for('users.login'))
    return render_template('reset_password_request.html',
                           title='Reset Password', form=form)



@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('core.index'))
    user = User.verify_reset_password_token(token)
    if not user:
        return redirect(url_for('core.index'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash('Your password has been reset.')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', form=form)


##################### rest password end ##############################

recipe_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

      <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/master.css') }}"/>

      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" />

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.css" />

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css" />

  <meta charset="utf-8">

    <title> Raj Recipe World</title>

  </head>

<body>

  <header class="py-5" >
    <!-- Nav-bar -->
<nav class="navbar navbar-expand-sm navbar-dark bg-info fixed-top ">
    <div class="container">

      <a href="{{ url_for('core.index') }}" target="_blank" class="navbar-brand"> <i class="fas fa-utensils icon-nav"></i> Recipe World</a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span> </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">




      <ul class="navbar-nav ml-auto">

    

            <li class="nav-item active">
              <a class="nav-link text-white" href="{{ url_for('core.index') }}">
                <i class="fas fa-home icon-nav"> Home </i>
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-white" href="{{ url_for('core.info') }}"> <i class="fas fa-users icon-nav"></i> About Us</a>
            </li>



        <!-- -->

            {% if current_user.is_authenticated %}



            <li class="nav-item">
                <a class="nav-link text-white" href="{{ url_for('users.logout') }}"> <i class="fas fa-sign-out-alt icon-nav"></i> Log Out </a>
            </li>

            <li class="nav-item">
                <a class="nav-link text-white" href="{{ url_for('users.account') }}">
                  <i class="fas fa-user icon-nav"> </i> Profile </a>
            </li>

            <li class="nav-item">
                <a class="nav-link text-white" href="{{ url_for('recipe_posts.create_recipe') }}">
                  <i class="fas fa-plus icon-nav"></i> Add Recipe</a>
            </li>

             <li class="nav-item"> 
                <a class="nav-link text-white" href="{{ url_for('users.user_recipies' , username=current_user.username) }}"> <i class="fas fa-user-circle icon-nav"> </i> {{ current_user }} </a>
              </li>



 

              {% else %}

              <li class="nav-item">
                  <a class="nav-link text-white" href="{{ url_for('users.login') }}"> <i class="fas fa-sign-in-alt icon-nav"></i> Log In </a>
              </li>


              
              <li class="nav-item">

                  <a href="{{ url_for('users.register') }}" class="btn btn-info btn-md">
                  <span class="glyphicon glyphicon-text-background"></span> Register
                </a>

              </li>



              {% endif %}

    </ul>
               
         

    
        
             
    </div>



       

   </div>

           
  
        

  </nav>

 </header>




  {% block content %}

  {% endblock %}


        <!-- FOOTER -->
         <footer id="main-footer" class="text-center p-4">
          <div class="container">
              <div class="row">
                <div class="col">

                    <a href="#"> <i class="fab fa-facebook-square fa-2x"> </i> </a>
                    <a href="#"> <i class="fab fa-youtube fa-2x"> </i> </a>
                    <a href="#"> <i class="fab fa-twitter-square fa-2x"></i> </a>
                    <a href="#"> <i class="fab fa-linkedin fa-2x"></i> </a>

                  <p> &copy;
                    <span id="year"></span> Raj Recipe World </p>
                </div>
              </div>
            </div>
          </footer>


    <!-- -->    <!-- -->    <!-- -->    <!-- -->    <!-- --> 

     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>
   <!-- -->    <!-- -->    <!-- -->    <!-- -->    <!-- --> 

recipe_app/templates/index.html
{% extends "base.html" %}
{% block content %}

<!-- -->   <!-- --> <!-- --> <!--   --> <!-- --> <!-- --> <!-- --> <!-- -->

<!-- Error Flash Message -->

<div>
    {% with messages = get_flashed_messages(with_categories=true) %}
  
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       {{ message }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

</div>
<!-- Error Flash Message End -->

<!-- -->   <!-- --> <!-- --> <!--   --> <!-- --> <!-- --> <!-- --> <!-- -->
<!-- -->   <!-- --> <!-- --> <!--   --> <!-- --> <!-- --> <!-- --> <!-- -->

  <!-- SHOWCASE SLIDER -->
  <section id="showcase" class="">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item carousel-image-1 active">
          <div class="container">
            <div class="carousel-caption d-none d-sm-block text-center mb-5">
              <h1 class="display-3 text-secondary"> Raj Recipe World</h1>
              <p class="lead text-danger"> Food Lover's Blog To Share The Recipe </p>
              <a href="{{ url_for('users.register') }}" class="btn btn-danger btn-lg">Sign Up Free</a>
            </div>
          </div>
        </div>

        <div class="carousel-item carousel-image-2">
          <div class="container">
            <div class="carousel-caption d-none d-sm-block mb-5">
             <h1 class="display-3 text-danger"> Raj Recipe World</h1>
              <span class="lead text-white bg-dark py-0"> Food Lover's Blog To Share The Recipe </span>
              <div class="py-4">
              <a href="{{ url_for('users.register') }}" class="btn btn-primary btn-lg">Register to Share</a>
              </div>
            </div>
          </div>
        </div>

        <div class="carousel-item carousel-image-3">
          <div class="container">
            <div class="carousel-caption d-none d-sm-block text-right mb-5">
             <h1 class="display-3 text-primary"> Raj Recipe World</h1>
              <p class="lead text-sucessy"> Food Lover's Blog To Share The Recipe </p>
              <a href="{{ url_for('users.register') }}" class="btn btn-success btn-lg">Register today</a>
            </div>
          </div>
        </div>
      </div>

      <a href="#myCarousel" data-slide="prev" class="carousel-control-prev">
        <span class="carousel-control-prev-icon"></span>
      </a>

      <a href="#myCarousel" data-slide="next" class="carousel-control-next">
        <span class="carousel-control-next-icon"></span>
      </a>
    </div>
  </section>

<!-- -->   <!-- --> <!-- --> <!--   --> <!-- --> <!-- --> <!-- --> <!-- -->



  <hr>

<!-- -->   <!-- --> <!-- --> <!--   --> <!-- --> <!-- --> <!-- --> <!-- -->

<section id="info" class="py-3">
  <div class="container">
    {# Go through each blog post #}

    {% for recipe in all_recipies_posts.items %}

    <div class="row">

      <div class="col-md-9 align-self-center">

        <h3> <a href="{{ url_for('recipe_posts.recipe_post', recipe_post_id=recipe.id) }}">{{ recipe.recipe_name }}</a> </h3>

          <p>

            Written by: <a href="{{ url_for('users.user_recipies', username = recipe.author.username) }}">{{ recipe.author.username }}</a>

            <br/>

            Published on: {{ recipe.date.strftime('%Y-%m-%d') }}
            <br/>

            {{ recipe.recipe_description[:100] }}...

            </p>

              <a href="{{ url_for('recipe_posts.recipe_post', recipe_post_id=recipe.id) }}" class="btn btn-outline-danger btn-lg">Read more</a>

              <hr>
               <br/>
                

          </div>

            <div class="col-md-3">
              <a href="{{ url_for('recipe_posts.recipe_post', recipe_post_id = recipe.id) }}"> <img src="{{recipe.recipe_image}}" alt="" class="img-fluid"> </a>
             </div>

           </div>

           {% endfor %}
  </div> <!-- container -->
</section>



<!-- -->   <!-- --> <!-- --> <!--   --> <!-- --> <!-- --> <!-- --> <!-- -->

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">

    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in all_recipies_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

            {% if all_recipies_posts.page == page_num %}

              <li class="page-item disabled">

                <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>

              </li>
             

            {% else %}

              <li class="page-item"> 

                <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>

              </li>
            {% endif %}

    {% endfor %}
  </ul>
</nav>
 <!-- --> <!-- --> <!--   --> <!-- --> <!-- --> <!-- --> <!-- -->
{% endblock %}
  <!-- --> <!-- --> <!--   --> <!-- --> <!-- --> <!-- --> <!-- -->
   <!-- --> <!-- --> <!--   --> <!-- --> <!-- --> <!-- --> <!-- -->
    <!-- --> <!-- --> <!--   --> <!-- --> <!-- --> <!-- --> <!-- -->
    <!-- --> <!-- --> <!--   --> <!-- --> <!-- --> <!-- --> <!-- -->

recipe_app/templates/user_recipe_posts.html
{% extends "base.html" %}
{% block content %}


<div>
    {% with messages = get_flashed_messages(with_categories=true) %}
  
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       {{ message }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

</div>


<!-- Error Flash Message End -->

<!-- -->
  <div class="py-1" style="height: 320px;">
    <div align='center'>
      <h2 >Welcome to the page for {{user.username}}</h2>

      <img class="img-fluid rounded-circle" align='center' style="height: 180px;" src="{{ (user.picture) }}">

    </div>
  </div>

<!-- -->
<!-- --> <!-- --> <!-- --><!-- --> <!-- --> <!-- -->
<!-- --> <!-- --> <!-- --> <!-- --> <!-- --><!-- -->

<section id="" class="py-3">
  <div class="container">
    <div class="row py-1">

 
      {% for recipe in recipies_posted.items %}


      <!-- -->
      <div class="col-md-8 align-self-center mt-4">

         <h2><a href="{{ url_for('recipe_posts.recipe_post', recipe_post_id = recipe.id) }}">{{ recipe.recipe_name }}</a></h2>

          Written by: <a href="{{ url_for('users.user_recipies', username = recipe.author.username) }}">{{ recipe.author.username }}</a>

          <p class="text-muted">Published on: {{ recipe.date.strftime('%Y-%m-%d') }}</p>

          <p>{{ recipe.recipe_description[:100] }}...</p>

          <a href="{{ url_for('recipe_posts.recipe_post', recipe_post_id = recipe.id) }}" class="btn btn-outline-danger btn-lg">Read more</a>
              
            {% if recipe.author == current_user %}

              <a class="btn btn-secondary" href="{{ url_for('recipe_posts.update', recipe_post_id = recipe.id) }}">Update</a>

               <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete </button>
              
                <hr>

            {% endif %}

      </div>  <!--col-md-8 -->

      <!-- -->

      <!-- -->
        <div class="col-md-4 py-2">
          <a href="{{ url_for('recipe_posts.recipe_post', recipe_post_id = recipe.id) }}"> <img src="{{recipe.recipe_image}}" alt="" class="img-fluid"> </a>

        </div>
      <!-- -->

      {% endfor %}

    </div> <!-- row -->
  </div> <!-- container-->
</section>
<hr>
<!-- -->
<!-- --> <!-- --> <!-- --><!-- --> <!-- --> <!-- -->
<!-- --> <!-- --> <!-- --> <!-- --> <!-- --><!-- -->
    <div>
  
    {% for recipe in recipies_posted.items %}

    <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Recipe </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete your <strong class="text-danger">  recipe post ??? </strong> </p>
        </div>
        
        <div class="modal-footer">
          
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('recipe_posts.delete_recipe', recipe_post_id=recipe.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
          
        </div>
        
      </div>
    </div>
  </div>

  
   {% endfor %}
</div>

<!-- --> <!-- --> <!-- --><!-- --> <!-- --> <!-- -->
<!-- --> <!-- --> <!-- --> <!-- --> <!-- --><!-- -->



<!-- -->
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">

    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in recipies_posted.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

            {% if recipies_posted.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_recipies', username=user.username, page=page_num) }}">{{ page_num }}</a>
              </li>
             

            {% else %}

              <li class="page-item"> <a class="page-link" href="{{ url_for('users.user_recipies', username=user.username, page=page_num) }}">{{ page_num }}</a>
              </li>
            {% endif %}

    {% endfor %}
  </ul>
</nav>
<!-- -->
<!-- --> <!-- --> <!-- --> <!-- --> <!-- --> <!-- --> <!-- --> 



{% endblock content %}